#!/bin/bash --login
#PBS -l nodes=1:ppn=32,walltime=10:00:00,mem=500gb
#PBS -m abe
#PBS -N ss       
. ~/intel.sh            
export PATH="/usr/local/bin:$PATH"

export OMP_NUM_THREADS=32
. ./ss.bat       
qstat -f $PBS_JOBID
