del/s fort.*    
del/s *.lp      
del/s *.trm     
del/s *.trf     
del/s *.tri     
del/s *.trd     
del/s *.mst     
del/s *.nba     
del/s *.prj     
del/s *.trl     
del/s *.abz     
del/s *.xvz     
del/s *.xvc     
del/s *.xva     
del/s *.nus     
del/s *.del     
del/s *.oph     
del/s *.op      
del/s *.me      
del/s *.addint  
del/s *.drt     
del/s *.JT      
del/s *.misV    
del/s *.sps     
del/s *.spe     
del/s *.prm     
del/s *.trb     
del/s *.tra     
del/s *.bxt     
del/s *.spt     
del/s *.npt     
del/s *.mpt     
del/s *.tmf     
del/s *.tdf     
del/s *.mat     
del/s *.mtx     
del/s *.sgt     
del/s *.ort     
del/s *.Jba     
del/s Set*.*    
del/s nuaddint.*
del/s *.trz     
del/s *.din     
del/s *.cpu     
del/s *vm.txt   
del/s *op.txt   
del/s *int.txt  
del/s *oph.txt  
del/s *.prd     
del/s *.lnz     
del/s transt.*  
del/s trans1.*  
del/s trans2.*  
del/s *.txi     
del/s *.lev     
del/s *.modelx  
del/s *.levelx  
del/s nucp.txt  
