nudel fort.*    
nudel *.lp      
nudel *.trm     
nudel *.trf     
nudel *.tri     
nudel *.trd     
nudel *.mst     
nudel *.nba     
nudel *.prj     
nudel *.trl     
nudel *.abz     
nudel *.xvz     
nudel *.xvc     
nudel *.xva     
nudel *.nus     
nudel *.del     
nudel *.oph     
nudel *.op      
nudel *.me      
nudel *.addint  
nudel *.drt     
nudel *.JT      
nudel *.misV    
nudel *.sps     
nudel *.spe     
nudel *.prm     
nudel *.trb     
nudel *.tra     
nudel *.bxt     
nudel *.spt     
nudel *.npt     
nudel *.mpt     
nudel *.tmf     
nudel *.tdf     
nudel *.mat     
nudel *.mtx     
nudel *.sgt     
nudel *.ort     
nudel *.Jba     
nudel Set*.*    
nudel nuaddint.*
nudel *.trz     
nudel *.din     
nudel *.cpu     
nudel *vm.txt   
nudel *op.txt   
nudel *int.txt  
nudel *oph.txt  
nudel *.prd     
nudel *.lnz     
nudel transt.*  
nudel trans1.*  
nudel trans2.*  
nudel *.txi     
nudel *.lev     
nudel *.modelx  
nudel *.levelx  
nudel nucp.txt  
